### PR TITLE
fix "y" the default to quit

### PR DESCRIPTION
**Pull request by vindarel**
Hello,

First of all: CONGRATS, this is really awesome ! There is room for more features (highlight matching parens, proper restarts…), but cl-repl already offers a lot and it fills a need. I really like it :)

In this PR:

- "y" is the default option when quitting (it didn't work)
- I didn't know how to test with roswell, so I added the ability to build an executable.

Thanks, see you !

### CODE REVIEW

**Comment by koji-kojiro** [comment]
Thanks to contribute!
I'm still a beginner on Common Lisp, and this is my first hack in CL. 
So I really appreciate it.

**Comment by koji-kojiro** [comment]
I'll check it later and then soon merge.

**Comment by koji-kojiro** [comment]
The executable does not seem to work as expected. (e.g. tab completion)
I always use a symlink from `~/.roswell/local-projects` to test my local projects with roswell. (see [FAQ of Roswell](https://github.com/roswell/roswell/wiki/FAQ#where-should-i-put-my-local-projects))

"y" seems to be fine for me.
To be honest, I could not understand what the commit tries to solve ...
Would you explain the meaning of added ""?

**Comment by vindarel** [comment]
Nice project for a first one :)

When I want to quit cl-repl, with C-d, I get the confirmation with "[y]/n": typing "y" works, but typing pressing Enter directly (which is supposed to quit, as says "[y]") did not quit, it asked again. 

You are right, tab completion does not work in the executable :(

**Comment by vindarel** [comment]
I removed the commit of the executable from the PR.

**Comment by koji-kojiro** [comment]
I got it now.
I designed the function by referring to ipython's behaviour.
But, I prefer this now.

Now I'm writing this comment from mobile, so I'll merge this PR later.

**Comment by vindarel** [comment]
ok cool :) I'm pretty sure this is ipython's behavior though.

**Comment by koji-kojiro** [comment]
I was a little confused...

> ok cool :) I'm pretty sure this is ipython's behavior though.

You are right al all. 
And this behaviour is what I truly expected.
Thanks.

**Pull request merged**
